build:
  tests:
    override:
      -
        command: 'phpunit -c phpunit-scrutinizer.xml'
  environment:
    php:
      version: 7.0.8
tools:
    external_code_coverage:
        timeout: 600
filter:
  paths: [src/*]
checks:
    php:
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        use_self_instead_of_fqcn: true
        use_statement_alias_conflict: true
        uppercase_constants: true
        uppercase_basic_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        security_vulnerabilities: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        require_braces_around_control_structures: true
        remove_trailing_whitespace: true
        remove_php_closing_tag: true
        property_assignments: true
        prefer_while_loop_over_for_loop: true
        prefer_unix_line_ending: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parameter_non_unique: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        optional_parameters_at_the_end: true
        non_commented_empty_catch_block: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_between_concatenation_operator: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_short_open_tag: true
        no_non_implemented_abstract_methods: true
        no_goto: true
        no_eval: true
        no_empty_statements: true
        no_else_if_statements: true
        no_debug_code: true
        missing_arguments: true
        method_calls_on_non_object: true
        lowercase_php_keywords: true
        instanceof_class_exists: true
        function_body_start_on_same_line: true
        foreach_usable_as_reference: true
        foreach_traversable: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_doc_comments: true
        ensure_lower_case_builtin_functions: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        code_rating: true
        closure_use_not_conflicting: true
        catch_class_exists: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_space_indentation: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        avoid_corrupting_byteorder_marks: true
        assignment_of_null_return: true
        argument_type_checks: true
        align_assignments: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        avoid_perl_style_comments: true

